package com.plataformaEducativa.proyectoestructuradatos.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "study_groups")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StudyGroup {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(nullable = false)
    private String name;
    
    private String description;
    
    @Column(name = "creation_date")
    private LocalDateTime creationDate;
    
    @ElementCollection
    @CollectionTable(name = "group_topics", joinColumns = @JoinColumn(name = "group_id"))
    @Column(name = "topic")
    private Set<String> topics = new HashSet<>();
    
    @ManyToMany(mappedBy = "studyGroups")
    private Set<User> members = new HashSet<>();
    
    @Column(name = "is_active")
    private boolean active = true;
    
    @Column(name = "auto_generated")
    private boolean autoGenerated = false;
    
    @PrePersist
    protected void onCreate() {
        creationDate = LocalDateTime.now();
    }
    
    public void addMember(User user) {
        members.add(user);
        user.getStudyGroups().add(this);
    }
    
    public void removeMember(User user) {
        members.remove(user);
        user.getStudyGroups().remove(this);
    }
}